// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: swift.flex

import java_cup.runtime.*;


// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
class Yylex implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\25\u0100\1\u0200\11\u0100\1\u0300\17\u0100\1\u0400\247\u0100"+
    "\10\u0500\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\2\3\1\4\22\0\1\1\1\5"+
    "\4\0\1\6\1\0\1\7\1\10\1\11\1\12\1\13"+
    "\1\14\1\15\1\16\12\17\1\20\1\21\1\22\1\23"+
    "\1\24\2\0\1\25\1\26\1\25\1\27\4\25\1\30"+
    "\21\25\1\31\1\32\1\33\1\32\1\25\1\32\1\34"+
    "\1\35\1\25\1\36\1\37\1\40\1\25\1\41\1\42"+
    "\2\25\1\43\1\25\1\44\1\45\1\46\1\25\1\47"+
    "\1\50\1\51\1\52\1\53\1\54\3\25\1\55\1\56"+
    "\1\57\7\0\1\3\32\0\1\1\u01df\0\1\1\177\0"+
    "\13\1\35\0\2\3\5\0\1\1\57\0\1\1\240\0"+
    "\1\1\377\0\u0100\60";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1536];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\5\0\1\1\2\2\1\3\1\1\1\4\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\4\21\1\22\1\23\11\21\1\24\1\1"+
    "\1\25\5\0\1\26\1\27\2\0\1\1\1\0\1\30"+
    "\1\31\1\32\1\33\3\21\1\34\3\21\1\35\5\21"+
    "\1\36\4\0\1\1\1\37\2\21\1\40\2\21\1\41"+
    "\1\42\2\21\1\43\1\21\1\44\1\1\1\45\1\21"+
    "\1\46\1\21\1\0\1\21\1\47\1\0\1\21\2\30"+
    "\1\21\1\50\2\51\1\0\1\52\1\53\1\30\1\54"+
    "\1\51\2\0\1\55\1\0\1\55\7\0";

  private static int [] zzUnpackAction() {
    int [] result = new int[122];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\61\0\142\0\223\0\304\0\365\0\365\0\u0126"+
    "\0\u0157\0\u0188\0\365\0\365\0\u01b9\0\u01b9\0\365\0\u01b9"+
    "\0\u01ea\0\u021b\0\u01b9\0\u024c\0\u027d\0\u02ae\0\u02df\0\u0310"+
    "\0\u0341\0\u0372\0\u03a3\0\365\0\365\0\u03d4\0\u0405\0\u0436"+
    "\0\u0467\0\u0498\0\u04c9\0\u04fa\0\u052b\0\u055c\0\365\0\u058d"+
    "\0\365\0\u05be\0\365\0\142\0\u05ef\0\u0620\0\365\0\365"+
    "\0\u0651\0\u0682\0\u06b3\0\u06e4\0\365\0\365\0\365\0\365"+
    "\0\u0715\0\u0746\0\u0777\0\u0310\0\u07a8\0\u07d9\0\u080a\0\u0310"+
    "\0\u083b\0\u086c\0\u089d\0\u08ce\0\u08ff\0\365\0\u0930\0\u05ef"+
    "\0\u0961\0\u0992\0\u09c3\0\u06e4\0\u09f4\0\u0a25\0\u0310\0\u0a56"+
    "\0\u0a87\0\u0310\0\u0ab8\0\u0ae9\0\u0b1a\0\u0b4b\0\u0b7c\0\u0961"+
    "\0\u0bad\0\u0310\0\u0bde\0\u0310\0\u0c0f\0\u0c40\0\u0c71\0\u0310"+
    "\0\u0ca2\0\u0cd3\0\u0d04\0\u0d35\0\u0d66\0\u0310\0\u0d97\0\u0dc8"+
    "\0\u0df9\0\u0310\0\u0310\0\u0e2a\0\u0310\0\u0e5b\0\u0e8c\0\u0ebd"+
    "\0\u0eee\0\u0f1f\0\u0e8c\0\u0f50\0\u0f81\0\u0fb2\0\u0fe3\0\u1014"+
    "\0\u1045\0\u1076";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[122];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\2\6\1\7\1\6\1\10\1\11\1\12\1\13\1\14"+
    "\1\15\1\16\1\17\1\20\1\6\1\21\1\22\1\23"+
    "\1\24\1\25\1\26\1\27\1\30\1\31\1\32\1\33"+
    "\1\34\1\6\1\35\2\30\1\36\1\37\1\40\1\30"+
    "\1\41\1\42\2\30\1\43\2\30\1\44\1\30\1\45"+
    "\1\46\1\47\1\50\1\51\1\6\43\0\1\52\15\0"+
    "\17\53\1\54\5\53\4\3\3\0\21\3\4\53\11\0"+
    "\2\55\1\0\1\55\3\0\1\55\57\0\1\56\124\0"+
    "\1\7\101\0\1\57\43\0\1\60\53\0\4\61\65\0"+
    "\1\62\4\0\1\63\57\0\1\64\1\0\1\22\51\0"+
    "\1\65\73\0\1\66\60\0\1\67\60\0\1\70\54\0"+
    "\1\30\5\0\4\30\3\0\21\30\23\0\1\30\5\0"+
    "\4\30\3\0\11\30\1\71\7\30\23\0\1\30\5\0"+
    "\4\30\3\0\11\30\1\72\7\30\23\0\1\30\5\0"+
    "\4\30\3\0\10\30\1\73\10\30\23\0\1\30\5\0"+
    "\4\30\3\0\11\30\1\74\7\30\23\0\1\30\5\0"+
    "\4\30\3\0\7\30\1\75\11\30\23\0\1\30\5\0"+
    "\4\30\3\0\1\76\10\30\1\77\7\30\23\0\1\30"+
    "\5\0\4\30\3\0\4\30\1\100\14\30\23\0\1\30"+
    "\5\0\4\30\3\0\3\30\1\101\15\30\23\0\1\30"+
    "\5\0\4\30\3\0\13\30\1\102\5\30\23\0\1\30"+
    "\5\0\4\30\3\0\13\30\1\103\5\30\23\0\1\30"+
    "\5\0\4\30\3\0\1\104\20\30\23\0\1\30\5\0"+
    "\4\30\3\0\5\30\1\105\13\30\62\0\1\106\41\0"+
    "\1\107\22\0\4\110\65\0\1\53\5\0\1\56\42\0"+
    "\4\61\4\0\1\111\47\0\11\62\1\112\47\62\2\63"+
    "\1\113\1\0\1\113\53\63\20\0\1\114\60\0\1\30"+
    "\5\0\4\30\3\0\11\30\1\115\7\30\23\0\1\30"+
    "\5\0\4\30\3\0\16\30\1\116\2\30\23\0\1\30"+
    "\5\0\4\30\3\0\15\30\1\117\3\30\23\0\1\30"+
    "\5\0\4\30\3\0\14\30\1\120\4\30\23\0\1\30"+
    "\5\0\4\30\3\0\7\30\1\121\11\30\23\0\1\30"+
    "\5\0\4\30\3\0\13\30\1\122\5\30\23\0\1\30"+
    "\5\0\4\30\3\0\15\30\1\123\3\30\23\0\1\30"+
    "\5\0\4\30\3\0\6\30\1\124\12\30\23\0\1\30"+
    "\5\0\4\30\3\0\16\30\1\125\2\30\23\0\1\30"+
    "\5\0\4\30\3\0\13\30\1\126\5\30\23\0\1\30"+
    "\5\0\4\30\3\0\6\30\1\127\12\30\55\0\1\55"+
    "\26\0\1\130\41\0\11\62\1\112\4\62\1\131\42\62"+
    "\2\0\1\113\1\0\1\113\51\0\1\113\21\0\1\30"+
    "\5\0\4\30\3\0\7\30\1\132\11\30\23\0\1\30"+
    "\5\0\4\30\3\0\1\30\1\133\17\30\23\0\1\30"+
    "\5\0\4\30\3\0\3\30\1\134\15\30\23\0\1\30"+
    "\5\0\4\30\3\0\14\30\1\135\4\30\5\0\4\136"+
    "\12\0\1\30\5\0\4\30\3\0\21\30\23\0\1\30"+
    "\5\0\4\30\3\0\10\30\1\137\10\30\23\0\1\30"+
    "\5\0\4\30\3\0\3\30\1\140\15\30\5\0\4\141"+
    "\12\0\1\30\5\0\4\30\3\0\21\30\23\0\1\30"+
    "\5\0\4\30\3\0\7\30\1\142\11\30\4\0\2\143"+
    "\3\62\4\143\1\144\46\143\1\62\17\0\1\30\5\0"+
    "\4\30\3\0\7\30\1\145\11\30\23\0\1\30\5\0"+
    "\4\30\3\0\3\30\1\146\15\30\4\0\1\147\4\150"+
    "\20\147\4\151\3\0\21\151\4\147\17\0\1\30\5\0"+
    "\4\30\3\0\15\30\1\152\3\30\5\0\4\141\20\0"+
    "\4\151\3\0\21\151\23\0\1\30\5\0\4\30\3\0"+
    "\3\30\1\153\15\30\4\0\1\62\4\143\4\62\1\112"+
    "\44\62\1\154\3\62\4\143\4\62\1\112\4\62\1\131"+
    "\37\62\1\154\2\62\17\0\1\30\5\0\4\30\3\0"+
    "\3\30\1\155\15\30\23\0\1\147\5\0\4\147\3\0"+
    "\21\147\4\0\1\147\4\150\20\147\4\156\3\0\21\156"+
    "\4\147\1\157\4\0\12\157\1\151\1\160\2\157\1\161"+
    "\1\157\4\151\3\157\21\151\4\157\2\62\1\154\1\62"+
    "\1\154\4\62\1\112\44\62\1\154\2\62\1\157\4\0"+
    "\12\157\1\156\1\160\2\157\1\161\1\157\4\156\3\157"+
    "\21\156\5\157\4\0\16\157\1\161\36\157\4\162\16\157"+
    "\1\161\35\157\1\163\4\0\16\163\1\161\35\163\1\0"+
    "\4\162\22\0\1\164\1\165\75\0\1\166\57\0\1\167"+
    "\66\0\1\170\57\0\1\157\44\0\1\171\66\0\1\172"+
    "\54\0\1\157\21\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4263];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\5\0\2\11\3\1\2\11\2\1\1\11\14\1\2\11"+
    "\11\1\1\11\1\1\1\11\1\0\1\11\1\1\2\0"+
    "\2\11\2\0\1\1\1\0\4\11\15\1\1\11\1\0"+
    "\1\1\2\0\23\1\1\0\2\1\1\0\7\1\1\0"+
    "\5\1\2\0\1\1\1\0\1\1\7\0";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[122];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** For the backwards DFA of general lookahead statements */
  private boolean [] zzFin = new boolean [ZZ_BUFFERSIZE+1];

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Yylex(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { 
            }
            // fall through
          case 46: break;
          case 2:
            { return new Symbol(sym.EOL);
            }
            // fall through
          case 47: break;
          case 3:
            { return new Symbol(sym.NO);
            }
            // fall through
          case 48: break;
          case 4:
            { return new Symbol(sym.AP);
            }
            // fall through
          case 49: break;
          case 5:
            { return new Symbol(sym.CP);
            }
            // fall through
          case 50: break;
          case 6:
            { return new Symbol(sym.MUL);
            }
            // fall through
          case 51: break;
          case 7:
            { return new Symbol(sym.SUM);
            }
            // fall through
          case 52: break;
          case 8:
            { return new Symbol(sym.COMA);
            }
            // fall through
          case 53: break;
          case 9:
            { return new Symbol(sym.RES);
            }
            // fall through
          case 54: break;
          case 10:
            { return new Symbol(sym.DIV);
            }
            // fall through
          case 55: break;
          case 11:
            { return new Symbol(sym.NUM, new Integer(yytext()));
            }
            // fall through
          case 56: break;
          case 12:
            { return new Symbol(sym.PP);
            }
            // fall through
          case 57: break;
          case 13:
            { return new Symbol(sym.PYC);
            }
            // fall through
          case 58: break;
          case 14:
            { return new Symbol(sym.LT);
            }
            // fall through
          case 59: break;
          case 15:
            { return new Symbol(sym.IGUAL);
            }
            // fall through
          case 60: break;
          case 16:
            { return new Symbol(sym.GT);
            }
            // fall through
          case 61: break;
          case 17:
            { return new Symbol(sym.IDENT, yytext());
            }
            // fall through
          case 62: break;
          case 18:
            { return new Symbol(sym.AC);
            }
            // fall through
          case 63: break;
          case 19:
            { return new Symbol(sym.CC);
            }
            // fall through
          case 64: break;
          case 20:
            { return new Symbol(sym.AL);
            }
            // fall through
          case 65: break;
          case 21:
            { return new Symbol(sym.CL);
            }
            // fall through
          case 66: break;
          case 22:
            { return new Symbol(sym.NE);
            }
            // fall through
          case 67: break;
          case 23:
            { return new Symbol(sym.AND);
            }
            // fall through
          case 68: break;
          case 24:
            { System.out.format("error");System.exit(0);
            }
            // fall through
          case 69: break;
          case 25:
            { return new Symbol(sym.LE);
            }
            // fall through
          case 70: break;
          case 26:
            { return new Symbol(sym.EQ);
            }
            // fall through
          case 71: break;
          case 27:
            { return new Symbol(sym.GE);
            }
            // fall through
          case 72: break;
          case 28:
            { return new Symbol(sym.DO);
            }
            // fall through
          case 73: break;
          case 29:
            { return new Symbol(sym.IF);
            }
            // fall through
          case 74: break;
          case 30:
            { return new Symbol(sym.OR);
            }
            // fall through
          case 75: break;
          case 31:
            { return new Symbol(sym.DOUBLE, new Double(yytext()));
            }
            // fall through
          case 76: break;
          case 32:
            { return new Symbol(sym.INT_TYPE);
            }
            // fall through
          case 77: break;
          case 33:
            { return new Symbol(sym.FOR);
            }
            // fall through
          case 78: break;
          case 34:
            { return new Symbol(sym.LET);
            }
            // fall through
          case 79: break;
          case 35:
            { return new Symbol(sym.VAR);
            }
            // fall through
          case 80: break;
          case 36:
            // general lookahead, find correct zzMarkedPos
            { int zzFState = 3;
              int zzFPos = zzStartRead;
              if (zzFin.length <= zzBufferL.length) {
                zzFin = new boolean[zzBufferL.length+1];
              }
              boolean zzFinL[] = zzFin;
              while (zzFState != -1 && zzFPos < zzMarkedPos) {
                zzFinL[zzFPos] = ((zzAttrL[zzFState] & 1) == 1);
                zzInput = Character.codePointAt(zzBufferL, zzFPos, zzMarkedPos);
                zzFPos += Character.charCount(zzInput);
                zzFState = zzTransL[ zzRowMapL[zzFState] + zzCMap(zzInput) ];
              }
              if (zzFState != -1) {
                zzFinL[zzFPos++] = ((zzAttrL[zzFState] & 1) == 1);
              }
              while (zzFPos <= zzMarkedPos) {
                zzFinL[zzFPos++] = false;
              }

              zzFState = 4;
              zzFPos = zzMarkedPos;
              while (!zzFinL[zzFPos] || (zzAttrL[zzFState] & 1) != 1) {
                zzInput = Character.codePointBefore(zzBufferL, zzFPos, zzStartRead);
                zzFPos -= Character.charCount(zzInput);
                zzFState = zzTransL[ zzRowMapL[zzFState] + zzCMap(zzInput) ];
              };
              zzMarkedPos = zzFPos;
            }
            { System.out.format("error");System.exit(0);
            }
            // fall through
          case 81: break;
          case 37:
            { return new Symbol(sym.BOOL_TYPE);
            }
            // fall through
          case 82: break;
          case 38:
            { return new Symbol(sym.ELSE);
            }
            // fall through
          case 83: break;
          case 39:
            { return new Symbol(sym.TRUE);
            }
            // fall through
          case 84: break;
          case 40:
            { return new Symbol(sym.FALSE);
            }
            // fall through
          case 85: break;
          case 41:
            // general lookahead, find correct zzMarkedPos
            { int zzFState = 1;
              int zzFPos = zzStartRead;
              if (zzFin.length <= zzBufferL.length) {
                zzFin = new boolean[zzBufferL.length+1];
              }
              boolean zzFinL[] = zzFin;
              while (zzFState != -1 && zzFPos < zzMarkedPos) {
                zzFinL[zzFPos] = ((zzAttrL[zzFState] & 1) == 1);
                zzInput = Character.codePointAt(zzBufferL, zzFPos, zzMarkedPos);
                zzFPos += Character.charCount(zzInput);
                zzFState = zzTransL[ zzRowMapL[zzFState] + zzCMap(zzInput) ];
              }
              if (zzFState != -1) {
                zzFinL[zzFPos++] = ((zzAttrL[zzFState] & 1) == 1);
              }
              while (zzFPos <= zzMarkedPos) {
                zzFinL[zzFPos++] = false;
              }

              zzFState = 2;
              zzFPos = zzMarkedPos;
              while (!zzFinL[zzFPos] || (zzAttrL[zzFState] & 1) != 1) {
                zzInput = Character.codePointBefore(zzBufferL, zzFPos, zzStartRead);
                zzFPos -= Character.charCount(zzInput);
                zzFState = zzTransL[ zzRowMapL[zzFState] + zzCMap(zzInput) ];
              };
              zzMarkedPos = zzFPos;
            }
            { System.out.format("error");System.exit(0);
            }
            // fall through
          case 86: break;
          case 42:
            { return new Symbol(sym.PRINT);
            }
            // fall through
          case 87: break;
          case 43:
            { return new Symbol(sym.WHILE);
            }
            // fall through
          case 88: break;
          case 44:
            { return new Symbol(sym.DOUBLE_TYPE);
            }
            // fall through
          case 89: break;
          case 45:
            // lookahead expression with fixed lookahead length
            zzMarkedPos = Character.offsetByCodePoints
                (zzBufferL, zzStartRead, zzEndRead - zzStartRead, zzMarkedPos, -1);
            { System.out.format("error");System.exit(0);
            }
            // fall through
          case 90: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
